### ISSUE TITLE
希望未来能有批量提取译文和批量应用译文功能

### ISSUE THREAD

**Issue by s63660807** [jsc6924/translation-assistant#16]
由于翻译过程中确定了术语库，有时需要一次性将所有中文文本中的某个日语词直接搜索替换，但是这样会导致双语文本中的日文原文部分也被替换，影响后续的编辑。目前是使用提取译文，在译文进行替换，再将译文应用到双语文本的方式。这个方式避免了搜索替换影响到日文文本，但是由于提取译文功能只能单个文件使用，操作比较繁琐。如果能有批量处理的功能，会快捷很多。

**Comment by jsc6924** [comment]
@s63660807 
3.24中实现了简单的批量替换（选中想替换的词然后右键），对于更复杂的批量操作，可以使用dltransform.yml（用起来麻烦不过功能是有的）

**Comment by s63660807** [comment]
我刚刚试了一下，确实可以用，这下替换译文的名字方便多了，谢谢。
不过使用dltransform.yml对于不懂代码的人是比较难的
