### ISSUE TITLE
[enhancement] 希望给侧边栏剪贴板添加直接输出到当前聚焦的活动编辑器功能

### ISSUE THREAD

**Issue by wzhydd1** [jsc6924/translation-assistant#2]
希望能在点击剪切板UI复制的同时能直接输出文本到编辑器，因为有时仅需要在当前位置粘贴一次，同时剩下的数字也不多了
也可以作为一个可选功能添加一个设置来控制

**Comment by jsc723** [comment]
![image](https://github.com/jsc6924/translation-assistant/assets/25193561/3e34d02c-b191-49bb-8390-4d79a550a0e5)
做成设置太麻烦了，添加一个按钮吧

**Comment by jsc723** [comment]
已更新
